// ============================================================================
// drum_engine.h - ADPCM 4-bit drum playback engine
//
// Decodes IMA-ADPCM drum samples from drum_data.{h,cpp} (auto-generated by
// gm_voice_extract), resamples from DRUM_SAMPLE_RATE to CFG_SAMPLE_RATE with
// linear interpolation, and mixes 'DRUM_VOICES' simultaneous voices into the
// time-domain audio buffer just before soft-clip.
//
// Memory: ~64 bytes per voice * DRUM_VOICES, plus the ADPCM byte array in
// flash (94 KB at 8 kHz from a standard GM kit; ~144 KB at 16 kHz).
// ============================================================================
#pragma once
#include <Arduino.h>

#ifndef DRUM_VOICES
#define DRUM_VOICES 8
#endif

// Initialize voices (call once in setup).
void drum_engine_init();

// Start a drum hit. midi_note is the percussion key (27-87 typically); velocity 0..127.
// Notes with no mapped sample are silently ignored.
void drum_engine_note_on(uint8_t midi_note, uint8_t velocity);

// Mix 'samples' drum samples into 'out' (additive). 'out' is the int32 buffer
// used by ps_render_block just before soft-clip.
void drum_engine_mix(int32_t* out, int samples);

// For diagnostics.
int  drum_engine_active_count();
